In [9]:
import pandas as pd
from transformers import pipeline
from tqdm.auto import tqdm

In [10]:
df = pd.read_csv("../../datasets/interview_questions/data_science.csv")
df.head()

,question,company,rating,position,date,comments
0,Write an SQL query that makes recommendations ...,Interviewed at Meta,3.9,Data Scientist,2 Mar 2016,40
1,You're about to get on a plane to Seattle. You...,Interviewed at Meta,3.9,Data Scientist,12 Sept 2013,34
2,Write a SQL query to compute a frequency table...,Interviewed at Meta,3.9,"Data Scientist, Analytics",6 Mar 2015,24
3,Given an list A of objects and another list B ...,Interviewed at Meta,3.9,Data Scientist,24 Mar 2017,19
4,Data challenge was very similar to the ads ana...,Interviewed at Meta,3.9,Data Scientist,10 May 2016,18

In [11]:
df = df.dropna(subset=['question'])
df = df[df['question'].str.strip() != ""]

In [12]:
sample_questions = df["question"].dropna().sample(
    n=min(100, len(df)),
    random_state=42
).tolist()

In [13]:
from google import genai

client = genai.Client(api_key='AIzaSyBvuMQB5wHXkR0TFdGBYgoSCWf6_LXoLRI')
prompt = f"""
These are interview questions from a dataset:

{sample_questions}

Identify the specific and not broad categories these questions belong to.
Return a numbered list of these categories without any extra information or formatting.
Maximum 10 categories
"""
response = client.models.generate_content(
    model='gemini-2.5-flash',
    contents=prompt
)

candidate_labels=[]
for line in response.text.splitlines():
    line = line.strip()
    if line and line[0].isdigit():
        category = line.split('.', 1)[1].strip()
        candidate_labels.append(category)

print(candidate_labels)

['Behavioral & Soft Skills', 'Project & Work Experience', 'Machine Learning & AI Concepts', 'SQL & Data Querying', 'Programming & Data Structures/Algorithms', 'Case Study & Product Sense', 'Statistical Concepts', 'Specific Tools & Technologies', 'Company & Role Motivation/Fit', 'Domain-Specific & Scientific Knowledge']

In [14]:
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli",device=0)

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

In [15]:
# predictions = []
# for question in tqdm(df['question']):
#     result = classifier(question,candidate_labels)
#     predictions.append(result['labels'][0])

# df['Predicted_Tag'] = predictions

In [16]:
results = classifier(df['question'].tolist(), candidate_labels, batch_size=32)
print(len(results)) 

predictions = []
for r in tqdm(results):
    predictions.append(r['labels'][0])

df['Predicted_Tag'] = predictions

10213

  0%|          | 0/10213 [00:00<?, ?it/s]

In [17]:
df["Predicted_Tag"].value_counts()

Predicted_Tag
Project & Work Experience                   2250
Behavioral & Soft Skills                    1812
Company & Role Motivation/Fit               1479
Domain-Specific & Scientific Knowledge       906
Specific Tools & Technologies                895
Statistical Concepts                         826
Case Study & Product Sense                   685
Machine Learning & AI Concepts               572
Programming & Data Structures/Algorithms     501
SQL & Data Querying                          287
Name: count, dtype: int64

In [18]:
df.head()

,question,company,rating,position,date,comments,Predicted_Tag
0,Write an SQL query that makes recommendations ...,Interviewed at Meta,3.9,Data Scientist,2 Mar 2016,40,SQL & Data Querying
1,You're about to get on a plane to Seattle. You...,Interviewed at Meta,3.9,Data Scientist,12 Sept 2013,34,Behavioral & Soft Skills
2,Write a SQL query to compute a frequency table...,Interviewed at Meta,3.9,"Data Scientist, Analytics",6 Mar 2015,24,SQL & Data Querying
3,Given an list A of objects and another list B ...,Interviewed at Meta,3.9,Data Scientist,24 Mar 2017,19,Machine Learning & AI Concepts
4,Data challenge was very similar to the ads ana...,Interviewed at Meta,3.9,Data Scientist,10 May 2016,18,SQL & Data Querying

In [19]:
df[['question','Predicted_Tag']].head(20)

,question,Predicted_Tag
0,Write an SQL query that makes recommendations ...,SQL & Data Querying
1,You're about to get on a plane to Seattle. You...,Behavioral & Soft Skills
2,Write a SQL query to compute a frequency table...,SQL & Data Querying
3,Given an list A of objects and another list B ...,Machine Learning & AI Concepts
4,Data challenge was very similar to the ads ana...,SQL & Data Querying
5,We have two options for serving ads within New...,Machine Learning & AI Concepts
6,"Consider a game with 2 players, A and B. Playe...",Case Study & Product Sense
7,Find the second largest element in a Binary Se...,Statistical Concepts
8,Given two tables\r\n\r\nFriend_request\r\n(req...,Statistical Concepts
9,Write a sql query to find out the overall frie...,SQL & Data Querying
10,Given the following tables how would you know ...,Behavioral & Soft Skills
11,1) Provided a table with user_id and dates the...,Specific Tools & Technologies
12,There is a table that tracks every time a user...,Machine Learning & AI Concepts
13,Behavioral questions probing about fit,Behavioral & Soft Skills
14,They asked probability question: \r\n\r\n1) T...,SQL & Data Querying
15,Write a function that takes in two sorted list...,Programming & Data Structures/Algorithms
16,"If 70% of Facebook users on iOS use Instagram,...",Case Study & Product Sense
17,Write a sorting algorithm for a numerical data...,Programming & Data Structures/Algorithms
18,Tell me about yourself,Behavioral & Soft Skills
19,The company developed a new feature and perfor...,Case Study & Product Sense